### ISSUE TITLE
Exact way to pass dark theme to codeBlockStyles prop

### ISSUE THREAD

**Issue by rohan-paul** [Joeyonng/react-jupyter-notebook#5]
Hi, 

First of Thanks a million for making such a great Library.

Just one question, I am passing dark theme to codeBlockStyles prop as below but its not changing the code theme. Probably I am missing something here.

```js

import { dark } from "react-syntax-highlighter/dist/esm/styles/prism"

...

<JupyterViewer
          rawIpynb={nb_test}
          displaySource="show"
          displayOutput="show"
          codeBlockStyles={{ style: dark }}
        />

```

**Comment by Joeyonng** [comment]
Hi @rohan-paul,

If you want to use another hljs theme, you can just pass the string name of the theme to the `codeBlockStyles` prop for `hljsStyle` property. 

This should work:

```Javascript
<JupyterViewer
   rawIpynb={nb_test}
   displaySource="show"
   displayOutput="show"
   codeBlockStyles={hljsStyle: "dark"}
/>
```

Let me know if you have more questions.

**Comment by rohan-paul** [comment]
Thanks, @Joeyonng for replying. I did like you advised, but dont see any changes in theme. My code is getting rendered as below ( i.e. it takes the default light theme whether I use `codeBlockStyles={{ hljsStyle: "dark" }}` or not )

![image](https://user-images.githubusercontent.com/12703975/144759398-516f0815-1a7a-4265-ade7-40c00dc25a57.png)

**Comment by rohan-paul** [comment]
Thanks, @Joeyonng  now it works perfectly.  Thanks so much for the help.
